package com.example.birthday.chatservice.service.impl;
import com.example.birthday.chatservice.client.UserClient; import com.example.birthday.chatservice.dto.*; import com.example.birthday.chatservice.exception.BusinessException; import com.example.birthday.chatservice.mapper.ChatMapper; import com.example.birthday.chatservice.model.*; import com.example.birthday.chatservice.repository.*; import com.example.birthday.chatservice.service.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.transaction.support.*; import java.util.*;
@Service public class ChatServiceImpl implements ChatService{
 private final ChatRoomRepository rooms;private final ChatParticipantRepository participants;private final ChatMessageRepository messages;private final UserClient users;private final ChatMapper mapper;private final ChatMessageDeliveryService delivery;
 public ChatServiceImpl(ChatRoomRepository r,ChatParticipantRepository p,ChatMessageRepository m,UserClient u,ChatMapper x,ChatMessageDeliveryService d){rooms=r;participants=p;messages=m;users=u;mapper=x;delivery=d;}
 @Transactional public ChatRoomResponse createBirthday(UUID userId,UUID targetId,CreateChatRequest q){if(userId.equals(targetId))throw new BusinessException(HttpStatus.UNPROCESSABLE_ENTITY,"User cannot create a birthday chat about self");users.get(targetId);var room=new ChatRoom();room.setType(ChatRoomType.BIRTHDAY_DISCUSSION);room.setTitle(q.title().trim());room.setTargetUserId(targetId);room.setCreatedByUserId(userId);room=rooms.saveAndFlush(room);add(room,userId);return mapper.toResponse(room);}
 @Transactional public ChatRoomResponse join(UUID userId,UUID roomId){var room=require(roomId);if(userId.equals(room.getTargetUserId()))throw new BusinessException(HttpStatus.FORBIDDEN,"Birthday person cannot access this chat");if(participants.existsByRoomIdAndUserIdAndLeftAtIsNull(roomId,userId))throw new BusinessException(HttpStatus.CONFLICT,"User is already a participant");users.get(userId);add(room,userId);return mapper.toResponse(room);}
 @Transactional(readOnly=true) public List<ChatRoomResponse> mine(UUID userId){return participants.findAllByUserIdAndLeftAtIsNull(userId).stream().map(p->mapper.toResponse(p.getRoom())).toList();}
 @Transactional(readOnly=true) public Page<ChatMessageResponse> messages(UUID userId,UUID roomId,Pageable p){assertAccess(userId,roomId);return messages.findAllByRoomIdAndDeletedAtIsNullOrderByCreatedAtDesc(roomId,p).map(mapper::toResponse);}
 @Transactional public ChatMessageResponse send(UUID userId,UUID roomId,SendMessageRequest q){assertAccess(userId,roomId);var m=new ChatMessage();m.setRoom(require(roomId));m.setSenderId(userId);m.setContent(q.content().trim());m=messages.saveAndFlush(m);var response=mapper.toResponse(m);if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){public void afterCommit(){delivery.deliver(response);}});return response;}
 @Transactional(readOnly=true) public void assertAccess(UUID userId,UUID roomId){var room=require(roomId);if(userId.equals(room.getTargetUserId())||!participants.existsByRoomIdAndUserIdAndLeftAtIsNull(roomId,userId))throw new BusinessException(HttpStatus.FORBIDDEN,"Chat access denied");}
 private ChatRoom require(UUID id){return rooms.findByIdAndDeletedAtIsNull(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"Chat not found"));}
 private void add(ChatRoom r,UUID u){var p=new ChatParticipant();p.setRoom(r);p.setUserId(u);participants.save(p);}
}
